services:
  api:
    image: ghcr.io/maxentr/skyjo/api:latest
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    depends_on:
      - redis
    ports:
      - "3001:3001"
    networks:
      - internal
      - external
    env_file:
      - .env
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - NODE_OPTIONS=--max-old-space-size=8192 --max-http-header-size=16384 --expose-gc --use-largepages=silent
    restart: on-failure:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

  redis:
    image: redis/redis-stack-server:latest
    command: >
      redis-server 
      --loadmodule /opt/redis-stack/lib/rejson.so 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory 10gb
      --maxmemory-policy noeviction
      --appendonly yes
      --appendfsync everysec
      --io-threads 4
      --tcp-keepalive 300
      --maxclients 10000
      --timeout 300
      --tcp-backlog 511
      --databases 16
      --loglevel notice
      --client-output-buffer-limit normal 0 0 0
      --client-output-buffer-limit replica 256mb 64mb 60
      --client-output-buffer-limit pubsub 32mb 8mb 60
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - internal
      - external
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    networks:
      - internal
      - external
    env_file:
      - .env
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped
    volumes:
      - seq-data:/data

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3002:3001
    restart: always

networks:
  internal:
    internal: true
  external:

volumes:
  redis-data:
  seq-data:
  uptime-kuma-data:
