packages:
  - apps/*
  - packages/*
  - packages/config/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - bufferutil
  - core-js
  - esbuild
  - lefthook
  - msgpackr-extract
  - sharp
  - utf-8-validate