export class Constants {
  static readonly ERROR = {
    GAME_NOT_FOUND: "game-not-found",
    GAME_ALREADY_EXISTS: "game-already-exists",
    PLAYER_NOT_FOUND: "player-not-found",
    PLAYER_BANNED: "player-banned",
    PLAYER_NOT_CONNECTED: "player-not-connected",
    NOT_ALLOWED: "not-allowed",
    INVALID_TURN_STATE: "invalid-turn-state",
    TOO_FEW_PLAYERS: "too-few-players",
    CANNOT_RECONNECT: "cannot-reconnect",
    GAME_IS_FULL: "game-is-full",
    GAME_ALREADY_STARTED: "game-already-started",
    KICK_VOTE_IN_PROGRESS: "kick-vote-in-progress",
    NO_KICK_VOTE_IN_PROGRESS: "no-kick-vote-in-progress",
    PLAYER_ALREADY_VOTED: "player-already-voted",
    UNKNOWN_OPERATION: "unknown-operation",
    STATE_VERSION_AHEAD: "state-version-ahead",
    STATE_VERSION_BEHIND: "state-version-behind",
    STATE_VERSION_NULL: "state-version-null",
    VERSION_MISMATCH: "version-mismatch",
    TOO_MANY_REQUESTS: "too-many-requests",
    GAME_ALREADY_PROCESSING_AFK: "game-already-processing-afk",
    PLAYER_ALREADY_CONNECTED: "player-already-connected",
    MAX_PLAYERS_TOO_LOW: "max-players-too-low",
    UNEXPECTED_ERROR: "unexpected-error",
    MESSAGE_NOT_FOUND: "message-not-found",
    UNAUTHORIZED: "unauthorized",
    INVALID_PIN: "invalid-pin",
    EXPIRED_PIN: "expired-pin",
    EMAIL_ALREADY_SENT: "email-already-sent",
    EMAIL_ALREADY_EXISTS: "email-already-exists",
    SESSION_TOKEN_MISSING: "session-token-missing",
    SESSION_INVALID: "session-invalid",
    LOGIN_INVALID_CREDENTIALS: "login-invalid-credentials",
    SESSION_NOT_FOUND: "session-not-found",
    LOGOUT_ERROR: "logout-error",
    USER_NOT_FOUND: "user-not-found",
    USERNAME_TAKEN: "username-taken",
    RESET_TOKEN_INVALID: "reset-token-invalid",
    RESET_TOKEN_EXPIRED: "reset-token-expired",
    USERNAME_CREATION_FAILED: "username-creation-failed",
    INVALID_REVERSION_TOKEN: "invalid-reversion-token",
    EXPIRED_REVERSION_TOKEN: "expired-reversion-token",
    ACCOUNT_DELETION_ALREADY_SCHEDULED: "account-deletion-already-scheduled",
    ACCOUNT_DELETION_SCHEDULE_FAILED: "account-deletion-schedule-failed",
    INVALID_CANCELLATION_TOKEN: "invalid-cancellation-token",
    EXPIRED_CANCELLATION_TOKEN: "expired-cancellation-token",
    USER_CREATION_FAILED: "user-creation-failed",
    INVALID_CURRENT_PASSWORD: "invalid-current-password",
    ACCOUNT_DELETION_FAILED: "account-deletion-failed",
  } as const

  static readonly BAN_ERROR = {
    NOT_ALLOWED: "not-allowed",
    PLAYER_NOT_FOUND: "player-not-found",
    PLAYER_BANNED: "player-banned",
    UNEXPECTED_ERROR: "unexpected-error",
  } as const
}
export type Error = (typeof Constants.ERROR)[keyof typeof Constants.ERROR]

export type BanError =
  (typeof Constants.BAN_ERROR)[keyof typeof Constants.BAN_ERROR]
