# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Docker network connections
host    all             all             172.18.0.0/16           scram-sha-256
host    all             all             192.168.0.0/16          scram-sha-256

# Replication for your user
local   replication     skymo                                   trust
host    replication     skymo           127.0.0.1/32            trust
host    replication     skymo           ::1/128                 trust
host    replication     skymo           172.18.0.0/16           scram-sha-256